// Generated by gencpp from file task1/Test.msg
// DO NOT EDIT!


#ifndef TASK1_MESSAGE_TEST_H
#define TASK1_MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task1
{
template <class ContainerAllocator>
struct Test_
{
  typedef Test_<ContainerAllocator> Type;

  Test_()
    : content()
    , number(0)  {
    }
  Test_(const ContainerAllocator& _alloc)
    : content(_alloc)
    , number(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _content_type;
  _content_type content;

   typedef int16_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::task1::Test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task1::Test_<ContainerAllocator> const> ConstPtr;

}; // struct Test_

typedef ::task1::Test_<std::allocator<void> > Test;

typedef boost::shared_ptr< ::task1::Test > TestPtr;
typedef boost::shared_ptr< ::task1::Test const> TestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task1::Test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task1::Test_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace task1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'task1': ['/home/sebastian/ROS/src/task1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::task1::Test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task1::Test_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task1::Test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task1::Test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task1::Test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task1::Test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task1::Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "457e7dfc51876192fa55da49de0e384a";
  }

  static const char* value(const ::task1::Test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x457e7dfc51876192ULL;
  static const uint64_t static_value2 = 0xfa55da49de0e384aULL;
};

template<class ContainerAllocator>
struct DataType< ::task1::Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task1/Test";
  }

  static const char* value(const ::task1::Test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task1::Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string content\n\
int16 number\n\
";
  }

  static const char* value(const ::task1::Test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task1::Test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.content);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task1::Test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task1::Test_<ContainerAllocator>& v)
  {
    s << indent << "content: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.content);
    s << indent << "number: ";
    Printer<int16_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK1_MESSAGE_TEST_H
