// Generated by gencpp from file exercise2/move.msg
// DO NOT EDIT!


#ifndef EXERCISE2_MESSAGE_MOVE_H
#define EXERCISE2_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <exercise2/moveRequest.h>
#include <exercise2/moveResponse.h>


namespace exercise2
{

struct move
{

typedef moveRequest Request;
typedef moveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move
} // namespace exercise2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise2::move > {
  static const char* value()
  {
    return "e107a27f216b950369e7480afd9738c6";
  }

  static const char* value(const ::exercise2::move&) { return value(); }
};

template<>
struct DataType< ::exercise2::move > {
  static const char* value()
  {
    return "exercise2/move";
  }

  static const char* value(const ::exercise2::move&) { return value(); }
};


// service_traits::MD5Sum< ::exercise2::moveRequest> should match 
// service_traits::MD5Sum< ::exercise2::move > 
template<>
struct MD5Sum< ::exercise2::moveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise2::move >::value();
  }
  static const char* value(const ::exercise2::moveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise2::moveRequest> should match 
// service_traits::DataType< ::exercise2::move > 
template<>
struct DataType< ::exercise2::moveRequest>
{
  static const char* value()
  {
    return DataType< ::exercise2::move >::value();
  }
  static const char* value(const ::exercise2::moveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise2::moveResponse> should match 
// service_traits::MD5Sum< ::exercise2::move > 
template<>
struct MD5Sum< ::exercise2::moveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise2::move >::value();
  }
  static const char* value(const ::exercise2::moveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise2::moveResponse> should match 
// service_traits::DataType< ::exercise2::move > 
template<>
struct DataType< ::exercise2::moveResponse>
{
  static const char* value()
  {
    return DataType< ::exercise2::move >::value();
  }
  static const char* value(const ::exercise2::moveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE2_MESSAGE_MOVE_H
